spring.cloud.nacos.discovery.enabled=true
spring.cloud.nacos.discovery.fail-fast=false
spring.cloud.nacos.discovery.metadata.context-path=/api

food.service.base-url=http://food-service/api
user.service.base-url=http://user-service/api
app.rag.milvus.uri=http://milvus-standalone:19530

management.endpoints.web.exposure.include=health,info
