CREATE DATABASE IF NOT EXISTS `nutrimind_user` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS `nutrimind_food` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS `nutrimind_meal` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
